app-name: attendee-viewer
initials: brs
language: gradle
github-app-repo-uri: "git@github.com:benjaminrstone/attendee-viewer.git"
github-pipelines-repo-uri: "git@github.com:benjaminrstone/training-pipelines.git"
cf-dev-api: https://api.run.pivotal.io
cf-dev-org: rscale-training-2
cf-dev-space: ben
cf-dev-hostname: attendee-viewer-bstone
cf-dev-domain: cfapps.io
cf-dev-manifest: manifest.yml
